# Generated by Django 5.2.4 on 2025-07-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('dead', 'Dead')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animaltype')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.breed')),
            ],
        ),
    ]
