# Generated by Django 5.2.4 on 2025-07-22 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_weightrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
    ]
