# Generated by Django 5.2.4 on 2025-07-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_weightrecord_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from_days', models.PositiveIntegerField()),
                ('age_to_days', models.PositiveIntegerField()),
                ('ideal_min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.breed')),
            ],
        ),
    ]
